FROM centos
ADD http://apache.spd.co.il/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz /apache-maven-3.3.9.tar.gz
RUN tar zxvf apache-maven-3.3.9.tar.gz
RUN rm -f apache-maven-3.3.9.tar.gz
